const {test}=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),ts=require('typescript')
const mod={exports:{}};new Function('exports','require','module',ts.transpileModule(fs.readFileSync(require('node:path').join(__dirname,'../lib/transaction-edit.ts'),'utf8'),{compilerOptions:{module:ts.ModuleKind.CommonJS,target:ts.ScriptTarget.ES2017}}).outputText)(mod.exports,require,mod)
const {balanceDelta,resizeAllocations,effects}=mod.exports
const old={account_id:'BT',amount:20,transaction_type:'expense',status:'posted'}
test('expense account switch refunds old account and debits new account',()=>assert.deepEqual(balanceDelta(old,{...old,account_id:'George'}),{BT:20,George:-20}))
test('amount changes, income switch and no-op apply only the difference',()=>{assert.deepEqual(balanceDelta(old,{...old,amount:30}),{BT:-10});assert.deepEqual(balanceDelta(old,{...old,transaction_type:'income'}),{BT:40});assert.deepEqual(balanceDelta(old,old),{})})
test('transfer reversal, source/destination changes and conversion refund both old sides',()=>{const tx={...old,transaction_type:'transfer',transfer_account_id:'Revolut'};assert.deepEqual(balanceDelta(tx,{...tx,account_id:'Revolut',transfer_account_id:'BT'}),{BT:40,Revolut:-40});assert.deepEqual(balanceDelta(tx,{...tx,transaction_type:'expense',transfer_account_id:null}),{Revolut:-20})})
test('repeated edits reconcile with a single final effect, including cents and negative balances',()=>{const starting={BT:80,George:100,Revolut:-10};let prior=old;for(const next of [{...old,account_id:'George',amount:20.01},{...old,transaction_type:'transfer',account_id:'George',transfer_account_id:'Revolut',amount:50.02},old]){for(const [id,delta]of Object.entries(balanceDelta(prior,next)))starting[id]=Math.round((starting[id]+delta)*100)/100;prior=next}assert.deepEqual(starting,{BT:80,George:100,Revolut:-10})})
test('allocation resizing reconciles exactly to cents and preserves metadata ids',()=>{const rows=[{id:'a',category_id:'cat',amount:1},{id:'b',category_id:null,amount:1},{id:'c',category_id:null,amount:1}];const scaled=resizeAllocations(rows,10);assert.deepEqual(scaled.map(r=>r.amount),[3.34,3.33,3.33]);assert.equal(scaled[0].id,'a')})
test('creation and deletion reverse each account effect exactly, including transfers and income',()=>{for(const tx of [old,{...old,transaction_type:'income'},{...old,transaction_type:'transfer',transfer_account_id:'Revolut'}]){const current=effects(tx),removed=effects({...tx,status:'void'});assert.deepEqual(removed,{});const delta=balanceDelta(tx,{...tx,transaction_type:'expense',amount:0,transfer_account_id:null});for(const [id,cents]of Object.entries(current))assert.equal(delta[id],-cents/100)}})

const {balanceChange,ledgerEffects}=mod.exports
test('OFF creation, editing and deletion never affect balances',()=>{const tx={...old,affects_balance:false};assert.deepEqual(effects(tx),{});assert.deepEqual(balanceDelta(tx,{...tx,account_id:'George',amount:99}),{});assert.deepEqual(balanceChange(tx,{...tx,status:'void'}),{});assert.deepEqual(effects({...old,affects_balance:'false'}),{})})
test('ON to OFF refunds only the existing effect; OFF to ON applies the selected account',()=>{assert.deepEqual(balanceDelta(old,{...old,affects_balance:false,account_id:'George',amount:99}),{BT:20});assert.deepEqual(balanceDelta({...old,affects_balance:false},{...old,account_id:'George',affects_balance:true}),{George:-20})})
test('transfer toggle undoes or applies both sides',()=>{const tx={...old,transaction_type:'transfer',transfer_account_id:'Revolut'};assert.deepEqual(balanceDelta(tx,{...tx,affects_balance:false}),{BT:20,Revolut:-20});assert.deepEqual(balanceDelta({...tx,affects_balance:false},{...tx,affects_balance:true}),{BT:-20,Revolut:20})})
test('historical reference is preserved when moving an account, toggling and deleting',()=>{const historical={...old,balance_baseline:{...old}};assert.deepEqual(ledgerEffects(historical),{});const moved={...historical,account_id:'George'};assert.deepEqual(balanceDelta(historical,moved),{BT:20,George:-20});assert.deepEqual(balanceDelta(moved,{...moved,affects_balance:false}),{BT:-20,George:20});assert.deepEqual(balanceChange(historical,{...historical,status:'void'}),{BT:20});assert.deepEqual(balanceChange({...historical,affects_balance:false},{...historical,status:'void',affects_balance:false}),{})})
