'use client'

import Image from 'next/image'
import AccountTransactions from './AccountTransactions'
import {useEffect,useState} from 'react'
import {getSupabaseClient} from '@/lib/supabase'
import { Banknote, Landmark, UserRound } from 'lucide-react'
import type { Account, MyLifeData, Transaction } from '@/lib/mylife-data'
import { accountAmounts, accountBank, accountOwner } from '@/lib/account-display'
import './AccountsWorkspace.css'

const accountTypes: Record<string,string> = {checking:'Cont curent',cash:'Numerar',credit_card:'Card de credit',savings:'Economii'}
const money = (amount:number,currency:string) => new Intl.NumberFormat('ro-RO',{style:'currency',currency:currency.trim()}).format(amount)
export default function AccountsWorkspace({accounts,loading,onSelectAccount,data,onSaved,selectedAccount,onBack,onSelectTransaction}:{selectedAccount?:Account;onBack:()=>void;onSelectTransaction:(tx:Transaction)=>void;accounts:Account[];loading:boolean;onSelectAccount:(account:Account)=>void;data:MyLifeData|null;onSaved:()=>void}) {
  const [draft,setDraft]=useState<Account|null>(null),[busy,setBusy]=useState(false),[error,setError]=useState(''),[confirm,setConfirm]=useState<{account:Account;action:string}|null>(null),[archived,setArchived]=useState<Account[]>([]),[showArchived,setShowArchived]=useState(false),[people,setPeople]=useState<{id:string;display_name:string}[]>([])
  const hid=data?.profile.householdId,live=data?.source==='live'
  useEffect(()=>{let alive=true;const client=getSupabaseClient();if(client&&live&&hid){void (async()=>{const members=await client.from('household_members').select('person:people!person_id(id,display_name)').eq('household_id',hid).eq('status','active');if(alive&&members.data)setPeople(members.data.flatMap(row=>row.person ? [row.person] : []) as unknown as {id:string;display_name:string}[]);const result=await client.from('finance_accounts').select('id,name,account_type,currency,institution,owner_person_id,opening_balance,credit_limit,updated_at,is_active,owner:people!owner_person_id(display_name)').eq('household_id',hid).eq('is_active',false);if(result.error){if(alive)setError(result.error.message)}else if(result.data){try{const rows=await Promise.all((result.data as unknown as Account[]).map(async account=>{const balance=await client.rpc('finance_account_balance',{p_account_id:account.id});if(balance.error)throw Error(balance.error.message);if(balance.data===null||!Number.isFinite(Number(balance.data)))throw Error('Soldul contului arhivat nu este disponibil.');return {...account,current_balance:Number(balance.data)}}));if(alive)setArchived(rows)}catch(error){if(alive)setError(error instanceof Error?error.message:'Conturile arhivate nu au putut fi încărcate.')}}})()}return()=>{alive=false}},[hid,live,data?.capturedAt])
  async function manage(action:string,account:Account){const client=getSupabaseClient();if(!client||busy||!live)return;setBusy(true);setError('');try{const result=await client.rpc('finance_manage_account',{p_household_id:hid,p_id:account.id||null,p_action:action,p_expected_updated_at:account.updated_at??null,p_values:{name:account.name,account_type:account.account_type,currency:account.currency.trim().toUpperCase(),institution:account.institution,owner_person_id:account.owner_person_id||null,opening_balance:Number(account.opening_balance),credit_limit:account.credit_limit===null?null:Number(account.credit_limit)}});if(result.error)throw Error(result.error.message);setDraft(null);setConfirm(null);if(action!=='edit'&&action!=='create')onBack();onSaved()}catch(e){setError(e instanceof Error?e.message:'Nu s-a putut salva contul.')}finally{setBusy(false)}}
  const displayed=showArchived?archived:accounts
  const groups = new Map<string,{owner:ReturnType<typeof accountOwner>;accounts:Account[]}>()
  for (const account of displayed) {
    const owner=accountOwner(account)
    const group=groups.get(owner.id) ?? {owner,accounts:[]}
    group.accounts.push(account);groups.set(owner.id,group)
  }
  const sorted=Array.from(groups.values()).sort((a,b)=>({Mircea:0,Andreea:1}[a.owner.name]??2)-({Mircea:0,Andreea:1}[b.owner.name]??2)||a.owner.name.localeCompare(b.owner.name))
  const panels = <>    {error&&<p role="alert" className="transactionEditError">{error}</p>}
    {confirm&&<div className="accountsEditor accountsConfirm" role="alert"><h3>{confirm.action==='delete'?'Ștergi':confirm.action==='archive'?'Arhivezi':'Reactivezi'} „{confirm.account.name}”?</h3><p>{confirm.action==='delete'?'Atenție: ștergerea este definitivă. Contul poate fi șters doar dacă nu are istoric financiar.':'Arhivarea păstrează tranzacțiile. Contul poate fi reactivat ulterior.'}</p><button disabled={busy} onClick={()=>void manage(confirm.action,confirm.account)}>{confirm.action==='delete'?'Confirmă ștergerea':'Confirmă'}</button><button disabled={busy} onClick={()=>setConfirm(null)}>Renunță</button></div>}
    {draft&&<form className="accountsEditor" onSubmit={e=>{e.preventDefault();void manage(draft.id?'edit':'create',draft)}}><h3>{draft.id?'Editează contul':'Cont nou'}</h3><fieldset disabled={busy}><label>Nume<input required maxLength={150} value={draft.name} onChange={e=>setDraft({...draft,name:e.target.value})}/></label><label>Proprietar<select value={draft.owner_person_id??''} onChange={e=>setDraft({...draft,owner_person_id:e.target.value||null})}><option value="">Cont comun</option>{people.map(person=><option key={person.id} value={person.id}>{person.display_name}</option>)}</select></label><label>Bancă<input value={draft.institution??''} placeholder="BT, BCR, Revolut…" onChange={e=>setDraft({...draft,institution:e.target.value})}/></label><label>Tip<select value={draft.account_type} onChange={e=>setDraft({...draft,account_type:e.target.value})}>{['checking','cash','savings','credit_card','overdraft','investment','loan_given','loan_received','mortgage','other_asset','other_liability'].map(type=><option key={type} value={type}>{accountTypes[type]??type.replace(/_/g,' ')}</option>)}</select></label><label>Monedă<input required pattern="[A-Z]{3}" maxLength={3} value={draft.currency.trim()} onChange={e=>setDraft({...draft,currency:e.target.value.toUpperCase()})}/></label><label>Sold de referință<input required type="number" step="0.01" value={draft.opening_balance} onChange={e=>setDraft({...draft,opening_balance:e.target.value})}/></label>{draft.account_type==='credit_card'&&<label>Limită credit<input min="0" type="number" step="0.01" value={draft.credit_limit??''} onChange={e=>setDraft({...draft,credit_limit:e.target.value||null})}/></label>}<p>Soldul actual include și modificările din tranzacții. Schimbarea soldului de referință cu 100 RON modifică soldul actual tot cu 100 RON.</p><div><button type="submit">{busy?'Se salvează…':'Salvează contul'}</button><button type="button" onClick={()=>setDraft(null)}>Renunță</button></div></fieldset></form>}
</>
  const selected=selectedAccount?(accounts.find(a=>a.id===selectedAccount.id)??archived.find(a=>a.id===selectedAccount.id)??selectedAccount):undefined
  if(selected)return <section className="accountsWorkspace"><AccountTransactions account={selected} data={data} loading={loading} onBack={()=>{if(!busy){setDraft(null);setConfirm(null);setError('');onBack()}}} onSelect={onSelectTransaction} actions={<div className="accountsCrudActions"><button disabled={!live||busy} onClick={()=>{setError('');setConfirm(null);setDraft(selected)}}>Editează</button><button disabled={!live||busy} onClick={()=>{setError('');setDraft(null);setConfirm({account:selected,action:selected.is_active===false?'restore':'archive'})}}>{selected.is_active===false?'Reactivează':'Arhivează'}</button><button className="accountsDeleteAction" disabled={!live||busy} onClick={()=>{setError('');setDraft(null);setConfirm({account:selected,action:'delete'})}}>Șterge</button></div>} management={panels}/></section>
  return <section className="accountsWorkspace"><div className="sectionTitle"><h2>Conturi</h2><span>{loading?'Se încarcă…':`${displayed.length} ${showArchived?'arhivate':'active'}`}</span></div>
    <div className="accountsToolbar"><button aria-pressed={showArchived} onClick={()=>setShowArchived(!showArchived)}>{showArchived?'Arată Conturi Active':'Arată Conturi Arhivate'}</button><div className="financeCreateAction"><button disabled={!live||busy} onClick={()=>{setError('');setDraft({id:'',name:'',account_type:'checking',currency:'RON',opening_balance:0,credit_limit:null,owner_person_id:null,institution:''})}}>+ Adaugă cont</button></div></div>
    {panels}
    {loading ? <div className="emptyState" role="status">Se încarcă conturile…</div> : !displayed.length ? <div className="emptyState">Nu există conturi în această listă.</div> : <div className="accountsOwnersLayout">{sorted.map(group=><section className="accountsOwnerSection" key={group.owner.id} aria-label={`Conturile ${group.owner.name}`}><header className="accountsOwnerHeader">{group.owner.photo ? <Image className="accountsPortrait" src={group.owner.photo} alt={group.owner.name} width={64} height={64}/> : <div className="accountsPortrait accountsAvatarFallback"><UserRound size={26}/></div>}<div><p>CONTURI PERSONALE</p><h3>{group.owner.name}</h3></div><span>{group.accounts.length} conturi</span></header><div className="accountsOwnerGrid">{group.accounts.map(account=><div className="accountsManagedCard" key={account.id}><AccountCard account={account} ownerName={group.owner.name} onSelect={()=>onSelectAccount(account)}/> </div>)}</div></section>)}</div>}
  </section>
}
function AccountCard({account,ownerName,onSelect}:{account:Account;ownerName:string;onSelect:()=>void}) {
  const bank=accountBank(account)
  const {balance,available,credit,color}=accountAmounts(account)
  const currency=account.currency.trim()
  const amountColor=credit && available!==null ? (available>0?'green':available===0?'neutral':'red') : color
  const title=account.name.split(ownerName).join('').replace(/\bRON\b|\(George\)/g,'').replace(/Card cumpărături/i,'Credit').replace(/Cash/i,'Numerar').replace(/\s+/g,' ').trim()
  return <button type="button" className="accountsBalanceCard" aria-label={`Vezi tranzacțiile ${account.name}`} onClick={onSelect}><header><div className="accountsBankIcon">{bank.icon?<Image src={bank.icon} alt={bank.name} width={32} height={32}/>:account.account_type==='cash'?<Banknote size={24}/>:<Landmark size={24}/>}</div><div><h4 title={account.name}>{title}</h4>{credit && available!==null && <span className="accountsAvailableLabel">Disponibil pe card</span>}<span>{bank.name} · {accountTypes[account.account_type] || account.account_type.replace(/_/g,' ')}</span></div></header><div className="accountsAmountArea"><span>{credit && available!==null?'Disponibil pe card':credit?'Sold card de credit':'Sold'}</span><strong className={`accountsAmount accountsAmount-${amountColor}`}>{money(available ?? balance,currency)}</strong></div>{credit && <div className="accountsCreditDetails">{balance<0?<p><span>Datorie</span><strong className="accountsAmount-red">−{money(Math.abs(balance),currency)}</strong></p>:<p><span>Sold card</span><strong>{money(balance,currency)}</strong></p>}{available===null && <small>Limita nu este disponibilă; disponibilul nu poate fi calculat.</small>}</div>}</button>
}
