'use client'

import Image from 'next/image'
import AccountTransactions from './AccountTransactions'
import {useEffect,useState} from 'react'
import {getSupabaseClient} from '@/lib/supabase'
import { ArrowLeft, ArrowRight, Banknote, Landmark, Link2, RefreshCw, UserRound } from 'lucide-react'
import type { Account, MyLifeData, Transaction } from '@/lib/mylife-data'
import { accountAmounts, accountBank, accountOwner } from '@/lib/account-display'
import './AccountsWorkspace.css'

const accountTypes: Record<string,string> = {checking:'Cont curent',cash:'Numerar',credit_card:'Card de credit',savings:'Economii'}
const money = (amount:number,currency:string) => new Intl.NumberFormat('ro-RO',{style:'currency',currency:currency.trim()}).format(amount)
type BankTransaction={id:string;status:string|null;made_on:string;amount:number;currency:string;description:string;merchant_name:string|null;merchant_category_code:string|null;finance_transaction_id?:string|null}
type BankAccount={id:string;name:string;currency:string;balance:number|null;available_amount:number|null;iban_last4:string|null;finance_account_id:string|null;transaction_count:number;transactions:BankTransaction[]}
type BankConnection={id:string;provider_name:string|null;provider_code:string|null;status:string;stage:string|null;last_synced_at:string|null;last_error_message:string|null;accounts:BankAccount[]}
type BankPayload={error?:string;connections?:BankConnection[];mode?:'test'|'live';connectUrl?:string;finance_account_id?:string|null;account?:Omit<BankAccount,'transaction_count'|'transactions'>;transactions?:BankTransaction[];total?:number;next_offset?:number|null;imported?:number;skipped?:number}
export default function AccountsWorkspace({accounts,loading,onSelectAccount,data,onSaved,selectedAccount,onBack,onSelectTransaction,onAdjustAccount}:{selectedAccount?:Account;onBack:()=>void;onSelectTransaction:(tx:Transaction)=>void;onAdjustAccount:(account:Account)=>void;accounts:Account[];loading:boolean;onSelectAccount:(account:Account)=>void;data:MyLifeData|null;onSaved:()=>void}) {
  const [draft,setDraft]=useState<Account|null>(null),[busy,setBusy]=useState(false),[error,setError]=useState(''),[confirm,setConfirm]=useState<{account:Account;action:string}|null>(null),[archived,setArchived]=useState<Account[]>([]),[showArchived,setShowArchived]=useState(false),[people,setPeople]=useState<{id:string;display_name:string}[]>([])
  const [bankConnections,setBankConnections]=useState<BankConnection[]>([]),[bankMode,setBankMode]=useState<'test'|'live'>('test'),[bankBusy,setBankBusy]=useState(false),[bankReady,setBankReady]=useState(false)
  const [bankPickerOpen,setBankPickerOpen]=useState(false)
  const [selectedBankAccount,setSelectedBankAccount]=useState<BankAccount|null>(null),[bankTransactions,setBankTransactions]=useState<BankTransaction[]>([]),[bankTransactionsTotal,setBankTransactionsTotal]=useState(0),[bankNextOffset,setBankNextOffset]=useState<number|null>(null),[bankTransactionsBusy,setBankTransactionsBusy]=useState(false)
  const [selectedBankTransactionIds,setSelectedBankTransactionIds]=useState<Set<string>>(new Set())
  const [bankImportConfirm,setBankImportConfirm]=useState(false),[bankImportAffectsBalance,setBankImportAffectsBalance]=useState(false)
  const hid=data?.profile.householdId,live=data?.source==='live'
  useEffect(()=>{
    const url=new URL(window.location.href),status=url.searchParams.get('bank')
    if(!status)return
    if(status==='no-accounts')setError('Revolut a fost autorizat, dar Enable Banking nu a returnat niciun cont. Pentru aplicația live restricționată, leagă mai întâi contul Andreei din Enable Banking, apoi încearcă din nou.')
    else if(status==='failed')setError('Conectarea Revolut nu a putut fi finalizată. Încearcă din nou după ce verifici contul permis în Enable Banking.')
    else if(status==='expired'||status==='invalid-state')setError('Sesiunea de conectare Revolut a expirat. Pornește din nou conectarea.')
    url.searchParams.delete('bank');window.history.replaceState({},'',url)
  },[])
  useEffect(()=>{let alive=true;const client=getSupabaseClient();if(client&&live&&hid){void (async()=>{const members=await client.from('household_members').select('person:people!person_id(id,display_name)').eq('household_id',hid).eq('status','active');if(alive&&members.data)setPeople(members.data.flatMap(row=>row.person ? [row.person] : []) as unknown as {id:string;display_name:string}[]);const result=await client.from('finance_accounts').select('id,name,account_type,currency,institution,owner_person_id,opening_balance,credit_limit,updated_at,is_active,owner:people!owner_person_id(display_name)').eq('household_id',hid).eq('is_active',false);if(result.error){if(alive)setError(result.error.message)}else if(result.data){try{const rows=await Promise.all((result.data as unknown as Account[]).map(async account=>{const balance=await client.rpc('finance_account_balance',{p_account_id:account.id});if(balance.error)throw Error(balance.error.message);if(balance.data===null||!Number.isFinite(Number(balance.data)))throw Error('Soldul contului arhivat nu este disponibil.');return {...account,current_balance:Number(balance.data)}}));if(alive)setArchived(rows)}catch(error){if(alive)setError(error instanceof Error?error.message:'Conturile arhivate nu au putut fi încărcate.')}}})()}return()=>{alive=false}},[hid,live,data?.capturedAt])
  async function bankRequest(path:string,init?:RequestInit){const client=getSupabaseClient();if(!client)throw Error('Supabase nu este disponibil.');const {data:session}=await client.auth.getSession();const token=session.session?.access_token;if(!token)throw Error('Sesiunea nu mai este validă.');const response=await fetch(path,{...init,headers:{...init?.headers,Authorization:'Bearer '+token}});const payload=await response.json() as BankPayload;if(!response.ok)throw Error(payload.error||'Conexiunea bancară nu este disponibilă.');return payload}
  async function loadBankConnections():Promise<BankConnection[]>{if(!live)return[];try{const payload=await bankRequest('/api/open-banking/enable-banking/status');const connections=payload.connections??[];setBankConnections(connections);setBankMode(payload.mode??'test');setBankReady(true);return connections}catch(reason){setBankReady(false);const message=reason instanceof Error?reason.message:'';if(!/relation .* does not exist|schema cache/i.test(message))setError(message);return[]}}
  useEffect(()=>{void loadBankConnections()},[live,data?.capturedAt]) // eslint-disable-line react-hooks/exhaustive-deps
  async function connectBank(bank:'revolut'|'bcr'|'bt'){if(bankBusy)return;setBankBusy(true);setError('');try{const payload=await bankRequest('/api/open-banking/enable-banking/connect',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({bank})});if(!payload.connectUrl)throw Error('Enable Banking nu a returnat pagina de conectare.');setBankPickerOpen(false);window.location.assign(payload.connectUrl)}catch(reason){setError(reason instanceof Error?reason.message:'Banca nu a putut fi conectată.');setBankBusy(false)}}
  async function refreshBanks(){if(bankBusy)return;setBankBusy(true);setError('');try{await bankRequest('/api/open-banking/enable-banking/refresh',{method:'POST'});await loadBankConnections()}catch(reason){setError(reason instanceof Error?reason.message:'Conturile bancare nu au putut fi actualizate.')}finally{setBankBusy(false)}}
  async function refreshSelectedBankAccount(){if(bankBusy||bankTransactionsBusy||!selectedBankAccount)return;setBankBusy(true);setError('');try{await bankRequest('/api/open-banking/enable-banking/refresh',{method:'POST'});const connections=await loadBankConnections();const refreshed=connections.flatMap(connection=>connection.accounts).find(account=>account.id===selectedBankAccount.id);if(!refreshed)throw Error('Contul Revolut nu a fost găsit după actualizare.');await loadBankTransactions(refreshed)}catch(reason){setError(reason instanceof Error?reason.message:'Contul Revolut nu a putut fi actualizat.')}finally{setBankBusy(false)}}
  async function deleteTestBankData(){if(bankBusy||!window.confirm('Ștergi conexiunile Mock ASPSP și toate conturile și tranzacțiile lor de test?'))return;setBankBusy(true);setError('');try{await bankRequest('/api/open-banking/enable-banking/test-data',{method:'DELETE'});setSelectedBankAccount(null);setBankTransactions([]);await loadBankConnections()}catch(reason){setError(reason instanceof Error?reason.message:'Datele bancare de test nu au putut fi șterse.')}finally{setBankBusy(false)}}
  async function loadBankTransactions(account:BankAccount,offset=0){if(bankTransactionsBusy)return;if(offset===0){setSelectedBankAccount(account);setSelectedBankTransactionIds(new Set());setBankTransactions([]);setBankTransactionsTotal(account.transaction_count);setBankNextOffset(null)}setBankTransactionsBusy(true);setError('');try{const payload=await bankRequest(`/api/open-banking/enable-banking/accounts/${encodeURIComponent(account.id)}/transactions?offset=${offset}&limit=50`);const rows=payload.transactions??[];if(offset===0&&payload.account)setSelectedBankAccount({...account,...payload.account});setBankTransactions(current=>offset===0?rows:[...current,...rows]);setBankTransactionsTotal(payload.total??rows.length);setBankNextOffset(payload.next_offset??null)}catch(reason){setError(reason instanceof Error?reason.message:'Tranzacțiile sincronizate nu au putut fi încărcate.')}finally{setBankTransactionsBusy(false)}}
  async function linkBankAccount(account:BankAccount,financeAccountId:string|null){if(bankBusy)return;setBankBusy(true);setError('');try{await bankRequest(`/api/open-banking/enable-banking/accounts/${encodeURIComponent(account.id)}/link`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({financeAccountId})});await loadBankConnections();setSelectedBankAccount(current=>current?.id===account.id?{...current,finance_account_id:financeAccountId}:current)}catch(reason){setError(reason instanceof Error?reason.message:'Conturile nu au putut fi asociate.')}finally{setBankBusy(false)}}
  async function importBankTransactions(){if(!selectedBankAccount||!selectedBankTransactionIds.size||bankBusy)return;setBankBusy(true);setError('');try{const payload=await bankRequest(`/api/open-banking/enable-banking/accounts/${encodeURIComponent(selectedBankAccount.id)}/import`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({transactionIds:Array.from(selectedBankTransactionIds),affectsBalance:bankImportAffectsBalance})});setBankImportConfirm(false);await loadBankTransactions(selectedBankAccount);onSaved();if((payload.imported??0)===0)setError('Tranzacțiile selectate erau deja importate.')}catch(reason){setError(reason instanceof Error?reason.message:'Tranzacțiile nu au putut fi importate.')}finally{setBankBusy(false)}}
  async function manage(action:string,account:Account){const client=getSupabaseClient();if(!client||busy||!live)return;setBusy(true);setError('');try{const result=await client.rpc('finance_manage_account',{p_household_id:hid,p_id:account.id||null,p_action:action,p_expected_updated_at:account.updated_at??null,p_values:{name:account.name,account_type:account.account_type,currency:account.currency.trim().toUpperCase(),institution:account.institution,owner_person_id:account.owner_person_id||null,opening_balance:Number(account.opening_balance),credit_limit:account.credit_limit===null?null:Number(account.credit_limit)}});if(result.error)throw Error(result.error.message);setDraft(null);setConfirm(null);if(action!=='edit'&&action!=='create')onBack();onSaved()}catch(e){setError(e instanceof Error?e.message:'Nu s-a putut salva contul.')}finally{setBusy(false)}}
  const displayed=showArchived?archived:accounts
  const groups = new Map<string,{owner:ReturnType<typeof accountOwner>;accounts:Account[]}>()
  for (const account of displayed) {
    const owner=accountOwner(account)
    const group=groups.get(owner.id) ?? {owner,accounts:[]}
    group.accounts.push(account);groups.set(owner.id,group)
  }
  const sorted=Array.from(groups.values()).sort((a,b)=>({Mircea:0,Andreea:1}[a.owner.name]??2)-({Mircea:0,Andreea:1}[b.owner.name]??2)||a.owner.name.localeCompare(b.owner.name))
  const connectedGroups=new Map<string,{owner:ReturnType<typeof accountOwner>|{id:string;name:string;photo:undefined};accounts:Array<{account:BankAccount;connection:BankConnection}>}>()
  for(const connection of bankConnections){
    for(const account of connection.accounts){
      const linkedAccount=accounts.find(candidate=>candidate.id===account.finance_account_id)
      const owner=linkedAccount?accountOwner(linkedAccount):{id:'unlinked',name:'Neasociate',photo:undefined}
      const group=connectedGroups.get(owner.id)??{owner,accounts:[]}
      group.accounts.push({account,connection});connectedGroups.set(owner.id,group)
    }
  }
  const connectedSorted=Array.from(connectedGroups.values()).sort((a,b)=>({Mircea:0,Andreea:1,Neasociate:2}[a.owner.name]??3)-({Mircea:0,Andreea:1,Neasociate:2}[b.owner.name]??3)||a.owner.name.localeCompare(b.owner.name))
  const panels = <>    {error&&<p role="alert" className="transactionEditError">{error}</p>}
    {confirm&&<div className="accountsEditor accountsConfirm" role="alert"><h3>{confirm.action==='delete'?'Ștergi':confirm.action==='archive'?'Arhivezi':'Reactivezi'} „{confirm.account.name}”?</h3><p>{confirm.action==='delete'?'Atenție: ștergerea este definitivă. Contul poate fi șters doar dacă nu are istoric financiar.':'Arhivarea păstrează tranzacțiile. Contul poate fi reactivat ulterior.'}</p><button disabled={busy} onClick={()=>void manage(confirm.action,confirm.account)}>{confirm.action==='delete'?'Confirmă ștergerea':'Confirmă'}</button><button disabled={busy} onClick={()=>setConfirm(null)}>Renunță</button></div>}
    {draft&&<form className="accountsEditor" onSubmit={e=>{e.preventDefault();void manage(draft.id?'edit':'create',draft)}}><h3>{draft.id?'Editează contul':'Cont nou'}</h3><fieldset disabled={busy}><label>Nume<input required maxLength={150} value={draft.name} onChange={e=>setDraft({...draft,name:e.target.value})}/></label><label>Proprietar<select value={draft.owner_person_id??''} onChange={e=>setDraft({...draft,owner_person_id:e.target.value||null})}><option value="">Cont comun</option>{people.map(person=><option key={person.id} value={person.id}>{person.display_name}</option>)}</select></label><label>Bancă<input value={draft.institution??''} placeholder="BT, BCR, Revolut…" onChange={e=>setDraft({...draft,institution:e.target.value})}/></label><label>Tip<select value={draft.account_type} onChange={e=>setDraft({...draft,account_type:e.target.value})}>{['checking','cash','savings','credit_card','overdraft','investment','loan_given','loan_received','mortgage','other_asset','other_liability'].map(type=><option key={type} value={type}>{accountTypes[type]??type.replace(/_/g,' ')}</option>)}</select></label><label>Monedă<input required pattern="[A-Z]{3}" maxLength={3} value={draft.currency.trim()} onChange={e=>setDraft({...draft,currency:e.target.value.toUpperCase()})}/></label><label>Sold de referință<input required type="number" step="0.01" value={draft.opening_balance} onChange={e=>setDraft({...draft,opening_balance:e.target.value})}/></label>{draft.account_type==='credit_card'&&<label>Limită credit<input min="0" type="number" step="0.01" value={draft.credit_limit??''} onChange={e=>setDraft({...draft,credit_limit:e.target.value||null})}/></label>}<p>Soldul actual include și modificările din tranzacții. Schimbarea soldului de referință cu 100 RON modifică soldul actual tot cu 100 RON.</p><div><button type="submit">{busy?'Se salvează…':'Salvează contul'}</button><button type="button" onClick={()=>setDraft(null)}>Renunță</button></div></fieldset></form>}
</>
  const selected=selectedAccount?(accounts.find(a=>a.id===selectedAccount.id)??archived.find(a=>a.id===selectedAccount.id)??selectedAccount):undefined
  if(selectedBankAccount){
    const groups=new Map<string,BankTransaction[]>()
    for(const transaction of bankTransactions){const key=transaction.made_on.slice(0,7);groups.set(key,[...(groups.get(key)??[]),transaction])}
    const linkedAccount=accounts.find(account=>account.id===selectedBankAccount.finance_account_id)
    const selectedConnection=bankConnections.find(connection=>connection.accounts.some(account=>account.id===selectedBankAccount.id))
    const selectableTransactions=bankTransactions.filter(transaction=>!transaction.finance_transaction_id)
    const allVisibleSelected=selectableTransactions.length>0&&selectableTransactions.every(transaction=>selectedBankTransactionIds.has(transaction.id))
    return <section className="accountsWorkspace openBankingHistory">
      <button className="openBankingBack" onClick={()=>{setSelectedBankAccount(null);setSelectedBankTransactionIds(new Set());setBankImportConfirm(false);setBankTransactions([]);setBankTransactionsTotal(0);setBankNextOffset(null);setError('')}}><ArrowLeft size={18}/> Înapoi la conturi</button>
      <header className="openBankingHistoryHeader"><div><span>CONT SINCRONIZAT · ENABLE BANKING</span><h2>{selectedBankAccount.name}</h2><p>{selectedBankAccount.iban_last4?`Cont •••• ${selectedBankAccount.iban_last4} · `:''}{bankTransactionsTotal} {bankTransactionsTotal===1?'tranzacție':'tranzacții'}</p></div><div className="openBankingHistoryBalance"><strong>{money(selectedBankAccount.available_amount??selectedBankAccount.balance??0,selectedBankAccount.currency)}</strong><button disabled={bankBusy||bankTransactionsBusy} onClick={()=>void refreshSelectedBankAccount()}><RefreshCw className={bankBusy?'openBankingSpinning':''} size={16}/>{bankBusy?'Se actualizează…':'Actualizează acum'}</button>{selectedConnection?.last_synced_at&&<small>Ultima sincronizare: {new Date(selectedConnection.last_synced_at).toLocaleString('ro-RO',{day:'2-digit',month:'short',hour:'2-digit',minute:'2-digit'})}</small>}</div></header>
      <section className="openBankingLinkPanel"><div><strong>Asociere cu MyLife</strong><span>Alege contul în care vor fi importate tranzacțiile.</span></div><label><span>Cont MyLife</span><select disabled={bankBusy} value={selectedBankAccount.finance_account_id??''} onChange={event=>void linkBankAccount(selectedBankAccount,event.target.value||null)}><option value="">Neasociat</option>{accounts.filter(candidate=>candidate.currency.trim().toUpperCase()===selectedBankAccount.currency.trim().toUpperCase()).map(candidate=><option key={candidate.id} value={candidate.id}>{candidate.name}</option>)}</select></label>{linkedAccount&&<small>Asociat cu „{linkedAccount.name}”. Poți selecta mai jos tranzacțiile pe care vrei să le imporți.</small>}</section>
      <div className="openBankingImportBar">{linkedAccount?<><span><strong>{selectedBankTransactionIds.size}</strong> selectate din {selectableTransactions.length} afișate</span><div><button disabled={bankBusy||selectableTransactions.length===0} onClick={()=>setSelectedBankTransactionIds(allVisibleSelected?new Set():new Set(selectableTransactions.map(transaction=>transaction.id)))}>{allVisibleSelected?'Deselectează toate':'Selectează toate afișate'}</button><button disabled={bankBusy||selectedBankTransactionIds.size===0} onClick={()=>setBankImportConfirm(true)}>Importă selectatele</button></div></>:<span>Asociază întâi acest cont cu un cont MyLife pentru a putea selecta și importa tranzacții.</span>}</div>
      {bankImportConfirm&&linkedAccount&&<section className="openBankingImportConfirm" role="dialog" aria-labelledby="open-banking-import-title"><div><h3 id="open-banking-import-title">Importă {selectedBankTransactionIds.size} {selectedBankTransactionIds.size===1?'tranzacție':'tranzacții'} în „{linkedAccount.name}”?</h3><p>Tranzacțiile vor apărea în MyLife și vor fi marcate ca importate din Revolut.</p></div><label className="openBankingBalanceChoice"><input type="checkbox" checked={bankImportAffectsBalance} onChange={event=>setBankImportAffectsBalance(event.target.checked)}/><span><strong>Afectează soldul actual</strong><small>{bankImportAffectsBalance?'Sumele selectate vor modifica soldul contului MyLife.':'Soldul rămâne neschimbat; util dacă el reflectă deja soldul sincronizat.'}</small></span></label><div className="openBankingImportActions"><button disabled={bankBusy} onClick={()=>void importBankTransactions()}>{bankBusy?'Se importă…':'Confirmă importul'}</button><button disabled={bankBusy} onClick={()=>setBankImportConfirm(false)}>Renunță</button></div></section>}
      {error&&<p role="alert" className="transactionEditError">{error}</p>}
      {bankTransactionsBusy&&bankTransactions.length===0?<div className="emptyState">Se încarcă tranzacțiile…</div>:bankTransactions.length===0?<div className="emptyState">Nu există tranzacții sincronizate pentru acest cont.</div>:<div className="openBankingMonthGroups">{Array.from(groups.entries()).map(([month,transactions])=><section key={month}><header><h3>{new Date(`${month}-01T12:00:00`).toLocaleDateString('ro-RO',{month:'long',year:'numeric'})}</h3><strong>{money(transactions.reduce((sum,transaction)=>sum+transaction.amount,0),transactions[0]?.currency??selectedBankAccount.currency)}</strong></header><div>{transactions.map(transaction=><div className={`openBankingHistoryRow${transaction.finance_transaction_id?' openBankingHistoryRowImported':''}`} key={transaction.id}>{linkedAccount&&!transaction.finance_transaction_id&&<input type="checkbox" aria-label={`Selectează ${transaction.merchant_name||transaction.description}`} checked={selectedBankTransactionIds.has(transaction.id)} onChange={()=>setSelectedBankTransactionIds(current=>{const next=new Set(current);if(next.has(transaction.id))next.delete(transaction.id);else next.add(transaction.id);return next})}/>}<div><strong>{transaction.merchant_name||transaction.description}</strong>{transaction.merchant_name&&transaction.description!==transaction.merchant_name&&<span>{transaction.description}</span>}<time dateTime={transaction.made_on}>{new Date(`${transaction.made_on}T12:00:00`).toLocaleDateString('ro-RO',{day:'2-digit',month:'long',year:'numeric'})}</time>{transaction.finance_transaction_id&&<span className="openBankingImportedLabel">Importată în MyLife</span>}</div><strong className={transaction.amount<0?'openBankingDebit':'openBankingCredit'}>{transaction.amount>0?'+':''}{money(transaction.amount,transaction.currency)}</strong></div>)}</div></section>)}</div>}
      {bankNextOffset!==null&&<button className="openBankingLoadMore" disabled={bankTransactionsBusy} onClick={()=>void loadBankTransactions(selectedBankAccount,bankNextOffset)}>{bankTransactionsBusy?'Se încarcă…':`Încarcă încă ${Math.min(50,bankTransactionsTotal-bankTransactions.length)}`}</button>}
    </section>
  }
  if(selected)return <section className="accountsWorkspace"><AccountTransactions account={selected} data={data} loading={loading} onBack={()=>{if(!busy){setDraft(null);setConfirm(null);setError('');onBack()}}} onSelect={onSelectTransaction} actions={<div className="accountsCrudActions"><button disabled={!live||busy} onClick={()=>onAdjustAccount(selected)}>Ajustare</button><button disabled={!live||busy} onClick={()=>{setError('');setConfirm(null);setDraft(selected)}}>Editează</button><button disabled={!live||busy} onClick={()=>{setError('');setDraft(null);setConfirm({account:selected,action:selected.is_active===false?'restore':'archive'})}}>{selected.is_active===false?'Reactivează':'Arhivează'}</button><button className="accountsDeleteAction" disabled={!live||busy} onClick={()=>{setError('');setDraft(null);setConfirm({account:selected,action:'delete'})}}>Șterge</button></div>} management={panels}/></section>
  return <section className="accountsWorkspace"><div className="sectionTitle"><h2>Conturi</h2><span>{loading?'Se încarcă…':`${displayed.length} ${showArchived?'arhivate':'active'}`}</span></div>
    <div className="accountsToolbar"><button aria-pressed={showArchived} onClick={()=>setShowArchived(!showArchived)}>{showArchived?'Arată Conturi Active':'Arată Conturi Arhivate'}</button><div className="accountsToolbarPrimary">{bankReady&&<button className="accountsBankConnect" disabled={!live||bankBusy} onClick={()=>setBankPickerOpen(true)}><Link2 size={16}/>{bankBusy?'Se deschide…':bankMode==='live'?'Conectează bancă':'Testează conectarea'}</button>}<div className="financeCreateAction"><button disabled={!live||busy} onClick={()=>{setError('');setDraft({id:'',name:'',account_type:'checking',currency:'RON',opening_balance:0,credit_limit:null,owner_person_id:null,institution:''})}}>+ Adaugă cont</button></div></div></div>
    {bankPickerOpen&&<section className="openBankingPicker" role="dialog" aria-modal="true" aria-labelledby="open-banking-picker-title"><div><h3 id="open-banking-picker-title">Ce bancă vrei să conectezi?</h3><p>Vei fi trimis la bancă pentru autentificare și aprobarea accesului.</p></div><div className="openBankingPickerBanks"><button disabled={bankBusy} onClick={()=>void connectBank('revolut')}><Image src="/accounts/revolut.png" width={38} height={38} alt=""/><span><strong>Revolut</strong><small>Conectează încă un cont Revolut</small></span><ArrowRight size={18}/></button><button disabled={bankBusy} onClick={()=>void connectBank('bcr')}><Image src="/accounts/bcr.png" width={38} height={38} alt=""/><span><strong>George BCR</strong><small>Conectează contul curent BCR</small></span><ArrowRight size={18}/></button><button disabled={bankBusy} onClick={()=>void connectBank('bt')}><Image src="/accounts/bt.png" width={38} height={38} alt=""/><span><strong>Banca Transilvania</strong><small>Conectează unul sau mai multe conturi BT</small></span><ArrowRight size={18}/></button></div><button className="openBankingPickerCancel" disabled={bankBusy} onClick={()=>setBankPickerOpen(false)}>Renunță</button></section>}
    {panels}
    {loading ? <div className="emptyState" role="status">Se încarcă conturile…</div> : !displayed.length ? <div className="emptyState">Nu există conturi în această listă.</div> : <div className="accountsOwnersLayout">{sorted.map(group=><section className="accountsOwnerSection" key={group.owner.id} aria-label={`Conturile ${group.owner.name}`}><header className="accountsOwnerHeader">{group.owner.photo ? <Image className="accountsPortrait" src={group.owner.photo} alt={group.owner.name} width={64} height={64}/> : <div className="accountsPortrait accountsAvatarFallback"><UserRound size={26}/></div>}<div><p>CONTURI PERSONALE</p><h3>{group.owner.name}</h3></div><span>{group.accounts.length} conturi</span></header><div className="accountsOwnerGrid">{group.accounts.map(account=><div className="accountsManagedCard" key={account.id}><AccountCard account={account} ownerName={group.owner.name} onSelect={()=>onSelectAccount(account)}/> </div>)}</div></section>)}</div>}
    {!showArchived&&connectedSorted.length>0&&<section className="connectedAccountsOverview" aria-label="Conturi conectate"><header className="connectedAccountsTitle"><div><span>ENABLE BANKING · {bankMode==='live'?'LIVE':'SANDBOX'}</span><h3>Conturi conectate</h3></div><div className="openBankingHeaderActions">{bankConnections.some(connection=>/mock/i.test(connection.provider_name??''))&&<button className="openBankingDeleteTest" disabled={bankBusy} onClick={()=>void deleteTestBankData()}>Șterge datele de test</button>}<button title="Actualizează conturile conectate" aria-label="Actualizează conturile conectate" disabled={bankBusy} onClick={()=>void refreshBanks()}><RefreshCw className={bankBusy?'openBankingSpinning':''} size={16}/></button></div></header><div className="connectedAccountsOwners">{connectedSorted.map(group=><section className="connectedAccountsOwner" key={group.owner.id} aria-label={`Conturile conectate ${group.owner.name}`}><header>{group.owner.photo?<Image className="connectedAccountsPortrait" src={group.owner.photo} alt="" width={34} height={34}/>:<div className="connectedAccountsPortrait connectedAccountsFallback"><UserRound size={18}/></div>}<div><h4>{group.owner.name}</h4><span>{group.accounts.length} {group.accounts.length===1?'cont conectat':'conturi conectate'}</span></div></header><div className="connectedAccountsList">{group.accounts.map(({account,connection})=><button type="button" key={account.id} aria-label={`Vezi detaliile contului conectat ${account.name}`} onClick={()=>void loadBankTransactions(account)}><span title={`${connection.provider_name||connection.provider_code||'Bancă conectată'}${account.iban_last4?` · •••• ${account.iban_last4}`:''}`}>{account.name}</span><strong>{money(account.available_amount??account.balance??0,account.currency)}</strong><ArrowRight size={16}/></button>)}</div></section>)}</div></section>}
  </section>
}
function AccountCard({account,ownerName,onSelect}:{account:Account;ownerName:string;onSelect:()=>void}) {
  const bank=accountBank(account)
  const {balance,available,credit,color}=accountAmounts(account)
  const currency=account.currency.trim()
  const amountColor=credit && available!==null ? (available>0?'green':available===0?'neutral':'red') : color
  const title=account.name.split(ownerName).join('').replace(/\bRON\b|\(George\)/g,'').replace(/Card cumpărături/i,'Credit').replace(/Cash/i,'Numerar').replace(/\s+/g,' ').trim()
  return <button type="button" className="accountsBalanceCard" aria-label={`Vezi tranzacțiile ${account.name}`} onClick={onSelect}><header><div className="accountsBankIcon">{bank.icon?<Image src={bank.icon} alt={bank.name} width={32} height={32}/>:account.account_type==='cash'?<Banknote size={24}/>:<Landmark size={24}/>}</div><div><h4 title={account.name}>{title}</h4>{credit && available!==null && <span className="accountsAvailableLabel">Disponibil pe card</span>}<span>{bank.name} · {accountTypes[account.account_type] || account.account_type.replace(/_/g,' ')}</span></div></header><div className="accountsAmountArea"><span>{credit && available!==null?'Disponibil pe card':credit?'Sold card de credit':'Sold'}</span><strong className={`accountsAmount accountsAmount-${amountColor}`}>{money(available ?? balance,currency)}</strong></div>{credit && <div className="accountsCreditDetails">{balance<0?<p><span>Datorie</span><strong className="accountsAmount-red">−{money(Math.abs(balance),currency)}</strong></p>:<p><span>Sold card</span><strong>{money(balance,currency)}</strong></p>}{available===null && <small>Limita nu este disponibilă; disponibilul nu poate fi calculat.</small>}</div>}</button>
}
