'use client'
import {useEffect,useRef,useState} from 'react'
import {createPortal} from 'react-dom'
import {GripVertical,Plus,Pencil,Trash2,ChevronDown,X} from 'lucide-react'
import type {CategoryRow,MyLifeData} from '@/lib/mylife-data'
import {categoryAppearance,categoryIcons,categoryColors,sortedCategories} from '@/lib/category-display'
import {getSupabaseClient} from '@/lib/supabase'
import CategoryIcon from './CategoryIcon'
import useCategoryReorder from './useCategoryReorder'
import './CategoriesWorkspace.css'
type Draft={id?:string;name:string;kind:string;parent_id:string|null;icon:string;color:string;is_active:boolean}
export default function CategoriesWorkspace({data,onSaved,kind,onKindChange,onCategoriesChange}:{onCategoriesChange:(rows:CategoryRow[])=>void;data:MyLifeData;onSaved:()=>void;kind:string;onKindChange:(kind:string)=>void}){
 const [draft,setDraft]=useState<Draft|null>(null),[busy,setBusy]=useState(false),[error,setError]=useState(''),[deleting,setDeleting]=useState<CategoryRow|null>(null)
 const [expanded,setExpanded]=useState<Set<string>>(()=>new Set())
 const editorDialog=useRef<HTMLDialogElement>(null)
 useEffect(()=>{if(draft&&!editorDialog.current?.open)editorDialog.current?.showModal()},[!!draft])
 function toggleCategory(id:string){setExpanded(previous=>{const next=new Set(previous);if(next.has(id))next.delete(id);else next.add(id);return next})}
 const rows=sortedCategories(data.categories.filter(c=>c.kind===kind)),live=data.source==='live'
 async function mutate(action:()=>PromiseLike<{error:{message:string}|null}>){if(busy)return;setBusy(true);setError('');try{const result=await action();if(result.error)throw Error(result.error.message);setDraft(null);setDeleting(null);onSaved()}catch(e){setError(e instanceof Error?e.message:'Operațiunea nu a reușit.')}finally{setBusy(false)}}
 function edit(row?:CategoryRow,parent?:CategoryRow){setError('');setDraft(row?{...row,...categoryAppearance(row)}:{name:'',kind,parent_id:parent?.id??null,...categoryAppearance(parent??{id:crypto.randomUUID(),name:''}),is_active:true})}
 const reorder=useCategoryReorder(data.categories,onCategoriesChange,setError)
 const ghostRow=data.categories.find(row=>row.id===reorder.ghost?.id)
 const forbidden=new Set<string>();if(draft?.id){forbidden.add(draft.id);let changed=true;while(changed){changed=false;for(const row of rows)if(row.parent_id&&forbidden.has(row.parent_id)&&!forbidden.has(row.id)){forbidden.add(row.id);changed=true}}}
 function tree(parent:string|null,depth=0):React.ReactNode{return rows.filter(c=>c.parent_id===parent).map(row=> <div className={`categoryBranch ${reorder.dragging===row.id?'categoryBranchDragging':''} ${reorder.ghost?.target===row.id?reorder.ghost.after?'categoryDropAfter':'categoryDropBefore':''}`} key={row.id}><div data-category-id={row.id} className={`categoryRow ${!row.is_active?'archived':''} ${reorder.dragging===row.id?'categoryDragging':''}`} style={{marginLeft:Math.min(depth,4)*18}}><button className="categoryDragHandle" aria-label={`Reordonează ${row.name}`} title="Trage pentru reordonare; cu tastatura folosește săgețile sus/jos" disabled={!live||busy||!row.household_id} onPointerDown={e=>reorder.start(e,row)} onKeyDown={e=>reorder.keyboard(e,row)}><GripVertical size={18}/></button><CategoryIcon category={row} categories={data.categories}/><div className="categoryName">{!row.parent_id&&rows.some(child=>child.parent_id===row.id)?<button type="button" className="categoryExpandToggle" aria-expanded={expanded.has(row.id)} aria-controls={`category-children-${row.id}`} aria-label={`${expanded.has(row.id)?'Ascunde':'Arată'} subcategoriile ${row.name}`} onClick={()=>toggleCategory(row.id)}><strong>{row.name}</strong><ChevronDown size={16}/></button>:<strong>{row.name}</strong>}<small>{!row.is_active?'Arhivată':depth?'Subcategorie':`${rows.filter(c=>c.parent_id===row.id).length} subcategorii`}</small></div><div className="categoryActions">{!row.parent_id&&<button aria-label={`Adaugă subcategorie în ${row.name}`} disabled={!live||busy} onClick={()=>edit(undefined,row)}><Plus size={16}/></button>}<button aria-label={`Editează ${row.name}`} disabled={!live||busy||!row.household_id} onClick={()=>edit(row)}><Pencil size={16}/></button><button aria-label={`Șterge ${row.name}`} disabled={!live||busy||!row.household_id} onClick={()=>{setDeleting(row);setError('')}}><Trash2 size={16}/></button></div></div><div id={`category-children-${row.id}`} hidden={!expanded.has(row.id)}>{tree(row.id,depth+1)}</div></div>)}
 return <section className="categoriesWorkspace"><div className="sectionTitle"><div><h2>Categorii</h2></div></div><div className="categoryKinds">{[['expense','Cheltuieli'],['income','Venituri'],['transfer','Transferuri']].map(([value,label])=><button key={value} aria-pressed={kind===value} onClick={()=>{onKindChange(value);setDraft(null);setDeleting(null);setExpanded(new Set())}}>{label}</button>)}</div><p className="categorySaveStatus" role="status">{reorder.saving?'Se salvează ordinea…':''}</p><span className="categoryReorderAnnouncement" aria-live="polite">{reorder.announcement}</span>{!live&&<p>Conectează-te pentru administrarea categoriilor.</p>}{error&&<p role="alert" className="transactionEditError">{error}</p>}{deleting&&<div className="categoryEditor"><h3>Ștergi „{deleting.name}”?</h3><p>Atenție: ștergerea este definitivă. Categoriile cu tranzacții sau subcategorii trebuie mai întâi eliberate. Le poți arhiva din editare pentru a păstra istoricul.</p><button disabled={busy} onClick={()=>{const client=getSupabaseClient();if(client)void mutate(()=>client.from('finance_categories').delete().eq('id',deleting.id).select('id').single())}}>Confirmă ștergerea</button><button disabled={busy} onClick={()=>setDeleting(null)}>Renunță</button></div>}{draft&&<dialog ref={editorDialog} className="categoryEditorSheet" aria-labelledby="category-editor-title" onClose={()=>{if(!busy)setDraft(null)}} onCancel={e=>{if(busy)e.preventDefault()}} onClick={e=>{if(!busy&&e.target===e.currentTarget)e.currentTarget.close()}}>
<header><h2 id="category-editor-title">{draft.id?'Editează categoria':draft.parent_id?'Subcategorie nouă':'Categorie nouă'}</h2><button type="button" aria-label="Închide" disabled={busy} onClick={()=>editorDialog.current?.close()}><X size={20}/></button></header>
<form className="categoryEditor" onSubmit={e=>{e.preventDefault();if(!draft.name.trim()){setError('Completează numele categoriei.');return}const client=getSupabaseClient();if(!client)return;const {id,...values}=draft;if(values.parent_id){const parent=rows.find(row=>row.id===values.parent_id);Object.assign(values,categoryAppearance(parent));}void mutate(()=>id?client.from('finance_categories').update({...values,name:values.name.trim()}).eq('id',id).select('id').single():client.from('finance_categories').insert({...values,name:values.name.trim(),household_id:data.profile.householdId,sort_order:Math.max(0,...rows.filter(c=>c.parent_id===draft.parent_id).map(c=>c.sort_order??0))+1}))}}>
<fieldset disabled={busy}><label>Nume<input required autoFocus maxLength={120} value={draft.name} onChange={e=>setDraft({...draft,name:e.target.value})}/></label><label>Categoria părinte<select aria-label="Categoria părinte" value={draft.parent_id??''} onChange={e=>setDraft({...draft,parent_id:e.target.value||null})}><option value="">Categorie principală</option>{rows.filter(c=>!c.parent_id&&!forbidden.has(c.id)&&c.household_id===data.profile.householdId&&(!draft.id||!rows.some(child=>child.parent_id===draft.id))).map(c=><option key={c.id} value={c.id}>{c.parent_id?'↳ ':''}{c.name}</option>)}</select></label>{!draft.parent_id&&<label>Iconiță<select aria-label="Iconiță" value={draft.icon} onChange={e=>setDraft({...draft,icon:e.target.value})}>{categoryIcons.map(icon=><option key={icon} value={icon}>{({tag:'Etichetă',food:'Mâncare',home:'Casă',car:'Mașină',health:'Sănătate',shield:'Asigurări',gift:'Cadouri',plane:'Călătorii',shopping:'Cumpărături',sport:'Sport',pet:'Animale',child:'Copil',wallet:'Venituri',utilities:'Utilități',coffee:'Cafea',education:'Educație'} as Record<string,string>)[icon]}</option>)}</select></label>} {!draft.parent_id&&<div className="categorySwatches">{categoryColors.map(color=><button key={color} type="button" aria-label={`Culoare ${color}`} aria-pressed={draft.color===color} style={{background:color}} onClick={()=>setDraft({...draft,color})}/>)}<input aria-label="Culoare personalizată" type="color" value={draft.color} onChange={e=>setDraft({...draft,color:e.target.value})}/><CategoryIcon category={{id:draft.id??'',name:draft.name,icon:draft.icon,color:draft.color}}/></div>}{draft.parent_id&&<p>Culoarea este moștenită de la categoria principală.</p>}<label><input type="checkbox" checked={draft.is_active} onChange={e=>setDraft({...draft,is_active:e.target.checked})}/> Activă în selectoarele de tranzacții</label><div><button type="submit">{busy?'Se salvează…':'Salvează categoria'}</button><button type="button" onClick={()=>editorDialog.current?.close()}>Renunță</button></div></fieldset></form></dialog>}{reorder.ghost&&ghostRow&&createPortal(<div className="categoryDragGhost" aria-hidden="true" style={{left:reorder.ghost.x,top:reorder.ghost.y,width:reorder.ghost.width,minHeight:reorder.ghost.height}}><GripVertical size={18}/><CategoryIcon category={ghostRow} categories={data.categories}/><div><strong>{ghostRow.name}</strong><small>Poziția {reorder.ghost.index+1} din {rows.filter(row=>row.parent_id===ghostRow.parent_id).length}{!ghostRow.parent_id&&rows.some(row=>row.parent_id===ghostRow.id)?' · cu subcategorii':''}</small></div></div>,document.body)}<div className="financeCreateAction"><button disabled={!live||busy} onClick={()=>edit()}><Plus size={18}/> Categorie nouă</button></div><div className="categoryTree">{tree(null)}{!rows.length&&<p>Nu există categorii. Adaugă prima categorie.</p>}</div></section>
}
