'use client'
import {useEffect,useMemo,useState} from 'react'
import Image from 'next/image'
import {Wallet,ArrowDownLeft,ArrowUpRight,Scale,ShoppingBag,Activity} from 'lucide-react'
import type {MyLifeData} from '@/lib/mylife-data'
import {getSupabaseClient} from '@/lib/supabase'
import {loadLoans,type Loan} from '@/lib/loans'
import {bucharestDay,buildExpenseReport} from '@/lib/expense-report'
import {financeOverview} from '@/lib/finance-overview'
import CategoryIcon from './CategoryIcon'
import './FinanceOverview.css'
export default function FinanceOverview({data,loading,onAccounts,onLoans,onReports}:{data:MyLifeData|null;loading:boolean;onAccounts:()=>void;onLoans:()=>void;onReports:()=>void}){
 const [currency,setCurrency]=useState('RON'),[loans,setLoans]=useState<Loan[]|null>(null),[loanError,setLoanError]=useState(''),[price,setPrice]=useState(''),[reserve,setReserve]=useState('')
 const hid=data?.source==='live'?data.profile.householdId:null
 useEffect(()=>{let cancelled=false;setLoans(null);setLoanError('');const client=getSupabaseClient();if(hid&&client)loadLoans(client,hid).then(rows=>{if(!cancelled)setLoans(rows)}).catch(e=>{if(!cancelled)setLoanError(e.message)});return()=>{cancelled=true}},[hid,data?.capturedAt])
 const today=bucharestDay(new Date()),model=useMemo(()=>financeOverview(data?.accounts??[],data?.transactions??[],loans,currency,today),[data,loans,currency,today])
 const currencies=[...new Set(['RON',...(data?.accounts??[]).map(a=>a.currency.trim()),...(data?.transactions??[]).map(t=>t.currency.trim()),...(loans??[]).map(l=>l.currency.trim())])]
 const money=(value:number)=>new Intl.NumberFormat('ro-RO',{style:'currency',currency}).format(value/100),signed=(value:number)=>`${value>0?'+':''}${money(value)}`,tone=(value:number)=>value<0?'negative':value>0?'positive':'neutral'
 const top=useMemo(()=>data&&currency==='RON'?buildExpenseReport(data.transactions,data.categories,data.splits,{from:today.slice(0,7)+'-01',to:today}).categories.slice(0,4):[],[data,currency,today])
 const priceNumber=Number(price.replace(',','.')),reserveNumber=Number(reserve.replace(',','.')),valid=price.trim()!==''&&Number.isFinite(priceNumber)&&priceNumber>=0&&Number.isFinite(reserveNumber)&&reserveNumber>=0
 const spendable=model.netBalance-(model.received??0),afterPurchase=spendable-Math.round((priceNumber+reserveNumber)*100)
 const monthLabel=new Date(today+'T12:00:00Z').toLocaleDateString('ro-RO',{month:'long',year:'numeric',timeZone:'UTC'}),max=Math.max(1,...model.months.flatMap(m=>[m.income,m.expenses]))
 if(loading||!data)return <div className="emptyState">{loading?'Se încarcă situația financiară…':'Conectează contul pentru situația financiară.'}</div>
 return <section className="financeOverview"><div className="sectionTitle"><div><h2>Overview</h2><p>O privire clară asupra banilor · {monthLabel}</p></div><label>Moneda<select aria-label="Moneda overview" value={currency} onChange={e=>setCurrency(e.target.value)}>{currencies.map(c=><option key={c}>{c}</option>)}</select></label></div>
 <div className="overviewOwners">{model.owners.map(owner=><article className="overviewWidget" key={owner.id}><header>{owner.photo&&<Image src={owner.photo} alt="" width={44} height={44}/>}<div><small>TOATE CONTURILE</small><h3>{owner.name}</h3></div></header><small>Bani disponibili · inclusiv credit</small><strong className={`overviewAmount ${tone(owner.available)}`}>{signed(owner.available)}</strong><dl><div><dt>Conturi curente și numerar</dt><dd>{money(owner.cash)}</dd></div><div><dt>Sold carduri de credit</dt><dd className={tone(owner.creditBalance)}>{money(owner.creditBalance)}</dd></div></dl><button onClick={onAccounts}>Vezi conturile →</button></article>)}</div>
 <div className="overviewGrid"><article className="overviewWidget"><header><Wallet/><h3>Banii familiei acum</h3></header><strong className={`overviewAmount ${tone(model.netBalance)}`}>{money(model.netBalance)}</strong><dl><div><dt>În conturi și numerar</dt><dd>{money(model.cash)}</dd></div><div><dt>Sold carduri de credit</dt><dd className={tone(model.creditBalance)}>{money(model.creditBalance)}</dd></div></dl><p>Totalul scade datoriile de credit. Limitele de credit nu sunt bani proprii.</p></article>
 <article className="overviewWidget"><header><Scale/><h3>Dacă închidem toate împrumuturile</h3></header><strong className={`overviewAmount ${model.afterLoans===null?'neutral':tone(model.afterLoans)}`}>{model.afterLoans===null?'—':money(model.afterLoans)}</strong><dl><div><dt>De primit</dt><dd className="positive">{model.given===null?'—':money(model.given)}</dd></div><div><dt>De restituit</dt><dd className="negative">{model.received===null?'—':money(model.received)}</dd></div><div><dt>Diferența împrumuturilor</dt><dd className={model.loanNet===null?'neutral':tone(model.loanNet)}>{model.loanNet===null?'—':signed(model.loanNet)}</dd></div></dl><p>Sold net + sumele de primit − sumele de restituit. Împrumuturile sunt evidențiate la nivelul familiei.</p>{loanError?<p role="alert">Împrumuturile nu au putut fi încărcate. <button onClick={onLoans}>Vezi împrumuturile</button></p>:!hid?<p>Conectează live pentru datele împrumuturilor.</p>:loans===null?<p role="status">Se încarcă împrumuturile…</p>:null}<button onClick={onLoans}>Vezi împrumuturile →</button></article>
 <article className="overviewWidget"><header><Activity/><h3>Balanța lunii curente</h3></header><strong className={`overviewAmount ${tone(model.current.net)}`}>{signed(model.current.net)}</strong><dl><div><dt><ArrowDownLeft size={14}/> Venituri</dt><dd className="positive">{money(model.current.income)}</dd></div><div><dt><ArrowUpRight size={14}/> Cheltuieli</dt><dd className="negative">{money(model.current.expenses)}</dd></div></dl><p>{model.current.count===0?'Nu sunt venituri sau cheltuieli înregistrate luna aceasta.':model.current.net<0?'Cheltuielile înregistrate depășesc veniturile luna aceasta.':'Veniturile înregistrate acoperă cheltuielile de până acum.'} Transferurile între conturi sunt excluse.</p><button onClick={onReports}>Vezi rapoartele →</button></article>
 <article className="overviewWidget"><header><Activity/><h3>Ritmul cheltuielilor</h3></header><strong className="overviewAmount">{money(Math.round(model.daily))}<small> / zi</small></strong><dl><div><dt>Estimare la sfârșitul lunii</dt><dd>{money(model.projected)}</dd></div><div><dt>Zile rămase</dt><dd>{model.daysLeft}</dd></div></dl><p>Estimare dacă media din primele {model.elapsed} zile se păstrează. Nu include facturi viitoare sau un buget stabilit.</p></article>
 <article className="overviewWidget overviewWide"><header><Activity/><h3>Venituri și cheltuieli · ultimele 6 luni</h3></header><div className="overviewLegend"><span className="positive">● Venituri</span><span className="negative">● Cheltuieli</span></div><div className="overviewChart">{model.months.map(m=><div className="overviewMonth" key={m.key}><div className="overviewBars"><div className="overviewIncomeBar" style={{height:`${m.income/max*100}%`}}/><div className="overviewExpenseBar" style={{height:`${m.expenses/max*100}%`}}/></div><strong>{m.label}</strong><small className="positive">{money(m.income)}</small><small className="negative">{money(m.expenses)}</small></div>)}</div><p>Luna curentă include doar datele până astăzi. Ajustările de sold nu sunt venituri.</p></article>
 <article className="overviewWidget"><header><ShoppingBag/><h3>Îmi ajung banii pentru…?</h3></header><label>Preț · {currency}<input type="number" inputMode="decimal" min="0" step="0.01" value={price} onChange={e=>setPrice(e.target.value)} placeholder="Introdu prețul produsului"/></label><label>Rezervă pe care vrei s-o păstrezi · {currency}<input type="number" inputMode="decimal" min="0" step="0.01" value={reserve} onChange={e=>setReserve(e.target.value)} placeholder="0"/></label>{valid?<><strong className={`overviewAmount ${tone(afterPurchase)}`}>{money(afterPurchase)}</strong><p>{afterPurchase>=0?'Rămâne această sumă după cumpărare și rezerva aleasă.':'Prețul și rezerva depășesc suma rămasă după datorii.'}</p></>:<p>Introdu un preț valid pentru a vedea diferența.</p>}<p>Calcul prudent: bani proprii net, minus împrumuturile de restituit. Nu contează sumele încă de primit. Nu include alte obligații viitoare.</p>{loans===null&&<p>Împrumuturile sunt încă necunoscute; calculul este parțial.</p>}</article>
 {currency==='RON'&&<article className="overviewWidget"><header><Activity/><h3>Unde se duc banii luna aceasta</h3></header>{top.length?top.map(c=><div className="overviewCategory" key={c.id}><CategoryIcon category={c}/><div><strong>{c.name}</strong><div className="overviewCategoryTrack"><span style={{width:`${c.percent}%`,background:c.color}}/></div></div><strong>{money(Math.round(c.amount*100))}</strong></div>):<p>Nu sunt cheltuieli înregistrate până astăzi.</p>}<button onClick={onReports}>Explorează categoriile →</button></article>}
 </div></section>
}
