'use client'

import {useEffect,useMemo,useState} from 'react'
import {Activity,CalendarDays,ChevronRight,FileText,HeartPulse,Lungs,Moon,PersonStanding,Plus} from 'lucide-react'
import {getSupabaseClient} from '@/lib/supabase'
import type {DocumentRow} from '@/lib/mylife-data'
import {healthDocuments,healthDocumentTitle,loadHealthData,metricMeta,type HealthData,type HealthMeasurement,type HealthMetricType} from '@/lib/health-data'
import './HealthModule.css'

export type HealthTab='overview'|'visits'|'data'|'documents'

const emptyData:HealthData={visits:[],measurements:[]}

function latest(rows:HealthMeasurement[],type:HealthMetricType){return rows.find(row=>row.metric_type===type)}
function display(row:HealthMeasurement|undefined){if(!row)return '—';if(row.metric_type==='sleep_duration'){const h=Math.floor(row.value);const m=Math.round((row.value-h)*60);return h+' h'+(m?' '+m+' min':'')}return Number(row.value).toLocaleString('ro-RO',{maximumFractionDigits:1})}
function iconFor(type:HealthMetricType){if(type==='resting_heart_rate')return HeartPulse;if(type==='sleep_duration')return Moon;if(type==='respiratory_rate')return Lungs;if(type==='vo2_max')return PersonStanding;return Activity}

export default function HealthModule({connected,refreshVersion,documents,documentsLoading,tab,setTab,registerMobileBack}:{connected:boolean;refreshVersion:number;documents:DocumentRow[];documentsLoading:boolean;tab:HealthTab;setTab:(tab:HealthTab)=>void;registerMobileBack:(handler:(()=>boolean)|null)=>void;onChanged:()=>void}){
  const [data,setData]=useState<HealthData>(emptyData)
  const [loading,setLoading]=useState(connected)
  const [error,setError]=useState('')
  const docs=useMemo(()=>healthDocuments(documents),[documents])
  useEffect(()=>{let cancelled=false;if(!connected){setLoading(false);return}const client=getSupabaseClient();if(!client){setError('Supabase nu este disponibil.');setLoading(false);return}setLoading(true);loadHealthData(client).then(value=>{if(!cancelled)setData(value)}).catch(reason=>{if(!cancelled)setError(reason instanceof Error?reason.message:'Datele nu pot fi încărcate.')}).finally(()=>{if(!cancelled)setLoading(false)});return()=>{cancelled=true}},[connected,refreshVersion])
  useEffect(()=>{registerMobileBack(()=>{if(tab!=='overview'){setTab('overview');return true}return false});return()=>registerMobileBack(null)},[registerMobileBack,setTab,tab])
  return <section className="healthModule">{error&&<div className="healthError">{error}</div>}{tab==='overview'?<Overview data={data} docs={docs} loading={loading||documentsLoading} setTab={setTab}/>:tab==='visits'?<SimplePage title="Vizite" subtitle="Programări și istoricul consultațiilor." empty="Nu există încă vizite."/>:tab==='data'?<DataPage data={data}/>:<DocumentsPage docs={docs} loading={documentsLoading}/>}</section>
}

function Header({title,subtitle}:{title:string;subtitle?:string}){return <header className="healthHeader"><div><span>MYLIFE</span><h1>{title}</h1>{subtitle&&<p>{subtitle}</p>}</div></header>}

function Overview({data,docs,loading,setTab}:{data:HealthData;docs:DocumentRow[];loading:boolean;setTab:(tab:HealthTab)=>void}){const types:HealthMetricType[]=['resting_heart_rate','sleep_duration','respiratory_rate','vo2_max'];const next=data.visits.filter(v=>v.status==='planned'&&new Date(v.scheduled_at).getTime()>=Date.now()).sort((a,b)=>a.scheduled_at.localeCompare(b.scheduled_at))[0];return <div className="healthPage"><Header title="Sănătate"/><section className="healthHero"><div><time>{new Date().toLocaleDateString('ro-RO',{timeZone:'Europe/Bucharest',weekday:'long',day:'numeric',month:'long',year:'numeric'})}</time><h2>{data.measurements.length?'Datele tale de sănătate':'Începe jurnalul de sănătate'}</h2><p>MyLife îți organizează valorile, vizitele și documentele medicale într-un singur loc.</p><span className="healthHeroPill"><HeartPulse size={17}/>Date organizate</span></div><div className="healthHeroArt"><HeartPulse size={64}/></div></section><div className="healthMetricGrid">{types.map(type=>{const row=latest(data.measurements,type);const Icon=iconFor(type);return <button className={'healthMetricCard metric-'+type} key={type} onClick={()=>setTab('data')}><div className="healthMetricIcon"><Icon size={23}/></div><div className="healthMetricCopy"><span>{metricMeta[type].label}</span><strong>{display(row)} {row&&type!=='sleep_duration'&&<small>{metricMeta[type].unit}</small>}</strong><em>{row?'Ultima valoare':'Fără date'}</em></div><ChevronRight size={18}/></button>})}</div><section className="healthCard healthNextCard"><header><h3>Următoarea vizită</h3><button onClick={()=>setTab('visits')}>Vezi toate <ChevronRight size={16}/></button></header>{next?<button className="healthVisitPreview" onClick={()=>setTab('visits')}><div className="healthSquareIcon blue"><CalendarDays size={23}/></div><div><strong>{next.doctor_name||next.specialty}</strong><span>{next.specialty}</span></div><ChevronRight size={19}/></button>:<button className="healthEmptyRow" onClick={()=>setTab('visits')}><span>Nicio vizită programată</span><ChevronRight size={18}/></button>}</section><section className="healthCard healthDocsPreview"><header><h3>Documente medicale</h3><button onClick={()=>setTab('documents')}>Vezi toate <ChevronRight size={16}/></button></header>{loading?<p className="healthMuted">Se încarcă…</p>:docs.length?docs.slice(0,3).map(doc=><button key={doc.id} onClick={()=>setTab('documents')}><div className="healthSquareIcon document"><FileText size={20}/></div><div><strong>{healthDocumentTitle(doc)}</strong><span>{doc.issuer||doc.source_filename||'Document medical'}</span></div><ChevronRight size={18}/></button>):<button className="healthEmptyRow" onClick={()=>setTab('documents')}><span>Niciun document medical</span><ChevronRight size={18}/></button>}</section></div>}

function SimplePage({title,subtitle,empty}:{title:string;subtitle:string;empty:string}){return <div className="healthPage"><Header title={title} subtitle={subtitle}/><div className="healthEmptyPanel"><CalendarDays size={34}/><strong>{empty}</strong></div></div>}
function DataPage({data}:{data:HealthData}){return <div className="healthPage"><Header title="Date" subtitle="Valori și tendințe, fără interpretări medicale."/><section className="healthPeriodSummary"><Activity size={22}/><div><strong>Toate datele</strong><span>{data.measurements.length} înregistrări</span></div><em>Date personale</em></section><div className="healthEmptyPanel"><Plus size={34}/><strong>CRUD pentru valori urmează în pasul următor.</strong></div></div>}
function DocumentsPage({docs,loading}:{docs:DocumentRow[];loading:boolean}){return <div className="healthPage"><Header title="Documente" subtitle="Analize, imagistică, rețete și alte acte medicale."/><section className="healthDocumentList">{loading?<p className="healthMuted">Se încarcă…</p>:docs.length?docs.map(doc=><button key={doc.id}><div className="healthSquareIcon document"><FileText size={21}/></div><div><strong>{healthDocumentTitle(doc)}</strong><span>{doc.issuer||doc.source_filename||'Document medical'}</span></div><ChevronRight size={18}/></button>):<div className="healthEmptyPanel"><FileText size={34}/><strong>Niciun document</strong></div>}</section></div>}
