'use client'
import { useEffect, useState } from 'react'
import { getSupabaseClient } from '@/lib/supabase'
import { bucharestDay } from '@/lib/expense-report'
import {createLoan,loadLoans,loanTotals,remaining,repayLoan,type Loan,type LoanInput} from '@/lib/loans'
import './LoansWorkspace.css'
const money=(amount:number,currency:string)=>new Intl.NumberFormat('ro-RO',{style:'currency',currency:currency.trim()}).format(amount)
const emptyInput=():LoanInput=>({direction:'given',counterparty:'',amount:'',currency:'RON',loan_date:bucharestDay(new Date()),purpose:'',notes:''})
export default function LoansWorkspace({householdId}:{householdId:string|null}) {
 const [loans,setLoans]=useState<Loan[]>([]),[loading,setLoading]=useState(false),[ready,setReady]=useState(false),[error,setError]=useState(''),[revision,setRevision]=useState(0),[showForm,setShowForm]=useState(false),[saving,setSaving]=useState(false),[input,setInput]=useState<LoanInput>(emptyInput),[repayment,setRepayment]=useState<{id:string;amount:string}|null>(null)
 useEffect(()=>{let cancelled=false;setLoans([]);setReady(false);setError('');setShowForm(false);setRepayment(null);if(!householdId){setLoading(false);return}const client=getSupabaseClient();if(!client)return;setLoading(true);loadLoans(client,householdId).then(data=>{if(!cancelled){setLoans(data);setReady(true)}}).catch(error=>{if(!cancelled)setError(error.message)}).finally(()=>{if(!cancelled)setLoading(false)});return()=>{cancelled=true}},[householdId,revision])
 async function save(){const client=getSupabaseClient();if(!client||!householdId)return;setSaving(true);setError('');try{const loan=await createLoan(client,householdId,input);setLoans(old=>[loan,...old].sort((a,b)=>b.loan_date.localeCompare(a.loan_date)));setShowForm(false);setInput(emptyInput())}catch(error){setError(error instanceof Error?error.message:'Împrumutul nu a fost salvat.')}finally{setSaving(false)}}
 async function repay(loan:Loan){const client=getSupabaseClient();if(!client||!repayment)return;setSaving(true);setError('');try{const updated=await repayLoan(client,loan,Number(repayment.amount.replace(',','.')));setLoans(old=>old.map(item=>item.id===updated.id?updated:item));setRepayment(null)}catch(error){setError(error instanceof Error?error.message:'Rambursarea nu a fost salvată.')}finally{setSaving(false)}}
 const field=<K extends keyof LoanInput>(key:K,value:LoanInput[K])=>setInput(old=>({...old,[key]:value}))
 return <section className="loansWorkspace"><div className="sectionTitle"><h2>Împrumuturi</h2><div className="loansActions"><button type="button" disabled={!householdId||loading||saving} onClick={()=>setRevision(v=>v+1)}>Actualizează</button><button type="button" disabled={!ready||saving} onClick={()=>{setInput(emptyInput());setShowForm(v=>!v)}}>Adaugă împrumut</button></div></div><p className="loansHint">Evidență separată de soldurile conturilor. Totalurile reprezintă sumele rămase de rambursat.</p>{!householdId&&<div className="emptyState">Conectează live contul Supabase pentru a vedea și salva împrumuturi.</div>}{error&&<p className="loansError" role="alert">{error}</p>}{loading&&<div className="emptyState" role="status">Se încarcă împrumuturile…</div>}
 {showForm&&<form className="loansForm" onSubmit={event=>{event.preventDefault();void save()}}><h3>Împrumut nou</h3><label>Tip<select value={input.direction} onChange={e=>field('direction',e.target.value as LoanInput['direction'])}><option value="given">Împrumut dat</option><option value="received">Împrumut primit</option></select></label><label>{input.direction==='given'?'Cui ai dat':'De la cine ai primit'}<input required maxLength={200} value={input.counterparty} onChange={e=>field('counterparty',e.target.value)}/></label><label>Suma<input required type="number" inputMode="decimal" min="0.01" step="0.01" value={input.amount} onChange={e=>field('amount',e.target.value)}/></label><label>Moneda<select value={input.currency} onChange={e=>field('currency',e.target.value)}>{['RON','EUR','USD','GBP'].map(currency=><option key={currency}>{currency}</option>)}</select></label><label>Data<input required type="date" value={input.loan_date} onChange={e=>field('loan_date',e.target.value)}/></label><label>Pentru ce<input maxLength={1000} value={input.purpose??''} onChange={e=>field('purpose',e.target.value)}/></label><label className="loansWide">Notițe<textarea maxLength={4000} value={input.notes??''} onChange={e=>field('notes',e.target.value)}/></label><div className="loansActions loansWide"><button type="submit" disabled={saving}>{saving?'Se salvează…':'Salvează împrumutul'}</button><button type="button" disabled={saving} onClick={()=>setShowForm(false)}>Renunță</button></div></form>}
 <div className="loansColumns">{(['given','received'] as const).map(direction=>{const entries=loans.filter(loan=>loan.direction===direction),totals=loanTotals(loans,direction);return <section className="loansColumn" key={direction}><header><p>{direction==='given'?'DE PRIMIT':'DE PLĂTIT'}</p><h3>{direction==='given'?'Împrumuturi date':'Împrumuturi primite'}</h3><div className={direction==='given'?'loansPositive':'loansNegative'}>{!ready?'—':Object.keys(totals).length?Object.entries(totals).map(([currency,cents])=><strong key={currency}>{money(cents/100,currency)}</strong>):<strong>0 RON</strong>}</div></header>{ready&&!entries.length&&<div className="emptyState">Nu există împrumuturi {direction==='given'?'date':'primite'}.</div>}{entries.map(loan=><article className="loansEntry" key={loan.id}><div className="loansEntryHeading"><h4>{loan.counterparty}</h4><span>{remaining(loan)===0?'Rambursat integral':'Activ'}</span></div><time dateTime={loan.loan_date}>{new Date(loan.loan_date+'T12:00:00Z').toLocaleDateString('ro-RO',{timeZone:'UTC'})}</time>{loan.purpose&&<p>{loan.purpose}</p>}<dl><div><dt>Suma inițială</dt><dd>{money(Number(loan.amount),loan.currency)}</dd></div><div><dt>Rambursat</dt><dd>{money(Number(loan.repaid_amount),loan.currency)}</dd></div><div><dt>Rămas {direction==='given'?'de primit':'de plătit'}</dt><dd><strong>{money(remaining(loan),loan.currency)}</strong></dd></div></dl>{loan.notes&&<p className="loansHint">{loan.notes}</p>}{remaining(loan)>0&&(repayment?.id===loan.id?<form className="loansRepayment" onSubmit={e=>{e.preventDefault();void repay(loan)}}><label>Sumă rambursată · {loan.currency}<input required type="number" inputMode="decimal" min="0.01" max={remaining(loan)} step="0.01" value={repayment.amount} onChange={e=>setRepayment({id:loan.id,amount:e.target.value})}/></label><button disabled={saving} type="submit">Confirmă rambursarea</button><button disabled={saving} type="button" onClick={()=>setRepayment(null)}>Renunță</button></form>:<button disabled={saving} type="button" onClick={()=>setRepayment({id:loan.id,amount:''})}>Notează rambursare</button>)}</article>)}</section>})}</div></section>
}
