import type { Transaction,SplitRow } from './mylife-data'
export type Allocation={id?:string;category_id:string|null;amount:number|string}
export type TransactionEdit={affects_balance?:boolean;transaction_type:string;account_id:string;transfer_account_id:string|null;amount:number;currency:string;day:string;title?:string;merchant:string;description:string;splits:Allocation[]}
export function effects(tx:Pick<Transaction,'transaction_type'|'account_id'|'transfer_account_id'|'amount'|'status'|'affects_balance'>){const result:Record<string,number>={};if(tx.affects_balance===false||tx.affects_balance==='false')return result;if(tx.status&&tx.status!=='posted')return result;const cents=Math.round(Number(tx.amount)*100);if(tx.account_id)result[tx.account_id]=['expense','transfer'].includes(tx.transaction_type)?-cents:cents;if(tx.transaction_type==='transfer'&&tx.transfer_account_id)result[tx.transfer_account_id]=(result[tx.transfer_account_id]??0)+cents;return result}
export function ledgerEffects(tx:Transaction){
 if(tx.affects_balance===false||tx.affects_balance==='false')return {}
 const current=effects(tx),baseline=tx.balance_baseline?effects(tx.balance_baseline):{}
 return Object.fromEntries([...new Set([...Object.keys(current),...Object.keys(baseline)])].map(id=>[id,(current[id]??0)-(baseline[id]??0)]).filter(([,amount])=>amount!==0)) as Record<string,number>
}
export function balanceChange(old:Transaction,next:Transaction){const before=ledgerEffects(old),after=ledgerEffects(next);return Object.fromEntries([...new Set([...Object.keys(before),...Object.keys(after)])].map((id):[string,number]=>[id,((after[id]??0)-(before[id]??0))/100]).filter(([,delta])=>delta!==0)) as Record<string,number>}
export function balanceDelta(old:Transaction,next:TransactionEdit){return balanceChange(old,{...next,status:'posted',id:old.id,transaction_date:old.transaction_date,balance_baseline:old.balance_baseline})}
export function resizeAllocations(rows:Allocation[],amount:number):Allocation[]{if(!rows.length)return rows;const cents=Math.round(amount*100),sum=rows.reduce((s,r)=>s+Math.round(Number(r.amount)*100),0);if(!Number.isFinite(cents)||cents<0)return rows;const raw=rows.map((row,index)=>({row,index,exact:sum?Number(row.amount)*100/sum*cents:index===0?cents:0}));const rounded=raw.map(r=>Math.floor(r.exact));let rest=cents-rounded.reduce((s,n)=>s+n,0);for(const r of [...raw].sort((a,b)=>(b.exact-Math.floor(b.exact))-(a.exact-Math.floor(a.exact))||a.index-b.index)){if(rest--<=0)break;rounded[r.index]++}return rows.map((row,i)=>({...row,amount:rounded[i]/100}))}
export function initialAllocations(rows:SplitRow[],amount:number):Allocation[]{const allocations:Allocation[]=rows.map(row=>({id:row.id,category_id:row.category_id,amount:Number(row.amount)}));const remainder=Math.round(amount*100)-allocations.reduce((s,row)=>s+Math.round(Number(row.amount)*100),0);if(remainder>0&&allocations.length)allocations.push({category_id:null,amount:remainder/100});return allocations}
